name: pyvertical-dev
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.*
  - numpy >=1.16
  - pandas >= 1.0.0
  - pytorch=1.10.*
  - torchvision
  - black  # for code formatting
  - pip >= 19
  - pip:
      - openmined.psi
      - pytest
      - matplotlib
      - syft==0.5.*
